#spring:
#  application:
#    name: goods-service
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/seata_demo
#    username: root
#    password: 3009
#  cloud:
#    consul:
#      discovery:
#        hostname: localhost
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#server:
#  port: 9002
#
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#
#mapper:
#  wrap-keyword: '`{0}`'
#
#cors:
#  allowedOrigins:
#    - http://localhost:9001
#  allowCredentials: true
#  allowedHeaders:
#    - "*"
#  allowedMethods:
#    - GET
#    - POST
#    - DELETE
#    - PUT
#    - OPTIONS
#    - HEAD
#  maxAge: 3600
#  filterPath: "/**"
#
#logging:
#  level:
#    com.aiway.seata: debug