spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_demo
    username: root
    password: 3009
  cloud:
    consul:
      discovery:
        hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9001

mybatis:
  configuration:
    map-underscore-to-camel-case: true

mapper:
  wrap-keyword: '`{0}`'


logging:
  level:
    com.aiway.seata: debug